# Generated by Django 3.0.5 on 2020-05-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lunedi'), (1, 'Martedi'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursedayhours',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedayhours',
            name='day',
        ),
        migrations.RemoveField(
            model_name='coursedayhours',
            name='hours',
        ),
        migrations.AddField(
            model_name='coursedayhours',
            name='hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Hours'),
        ),
        migrations.DeleteModel(
            name='CourseDayHoursHours',
        ),
        migrations.AddField(
            model_name='coursedayhours',
            name='coursedayhours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CourseDay'),
        ),
    ]
