# Generated by Django 3.0.7 on 2020-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0004_custommanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomManagement',
        ),
    ]
