# Generated by Django 3.0.7 on 2020-06-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_custommanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sex', verbose_name='Sesso'),
        ),
    ]
