# Generated by Django 3.0.7 on 2020-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200621_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='media/user_profile', verbose_name='Immagine del profilo'),
        ),
    ]
