# Generated by Django 3.0.7 on 2020-06-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200621_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sex',
            name='sex',
            field=models.CharField(max_length=50),
        ),
    ]
