# Generated by Django 3.0.8 on 2020-07-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibility', models.BooleanField(default=True, verbose_name='Disponibilità')),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
