# Generated by Django 3.0.8 on 2020-07-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismiss_prenotation', models.IntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(
                    choices=[(0, 'Lunedi'), (1, 'Martedi'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'),
                             (5, 'Sabato'), (6, 'Domenica')])),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('course',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Hours')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
